services:
  - type: web
    name: customer-intelligence-api
    env: python
    region: ohio
    plan: free
    repo: https://github.com/Yash-205/customerFeedback # Update if your repo URL is different
    branch: main
    rootDir: ai-engine
    buildCommand: |
      pip install -U pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL_ENDPOINT
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: NEO4J_USERNAME
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: NEO4J_URL_ENDPOINT
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
